# Removed obsolete version attribute

services:
  # Static website (existing)
  static_site:
    image: nginx:alpine
    ports:
      - "13124:80"
    volumes:
      - ./static_site:/usr/share/nginx/html
      - ./static_site/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/static:/usr/src/app/static
      - ./frontend/vite.config.ts:/usr/src/app/vite.config.ts
      - ./frontend/svelte.config.js:/usr/src/app/svelte.config.js
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clearpathtrade-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

volumes:
  node_modules:
