# Removed obsolete version attribute

services:
  # Static website
  static_site:
    build:
      context: ./static_site
      dockerfile: Dockerfile.prod
    ports:
      - "13124:80"
    volumes:
      - ./static_site:/usr/share/nginx/html
      - ./static_site/nginx.conf:/etc/nginx/nginx.conf

  # Svelte Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - backend

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://ollsoft:0lls0ft231!@postgres:5432/app_db
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=ollsoft
      - POSTGRES_PASSWORD=0lls0ft231!
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ollsoft"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  node_modules:
  postgres_data:
